(function (globalScope, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
    return;
  }

  globalScope.ExamListTemplateEditorRuntimeManifest = factory();
})(typeof globalThis !== "undefined" ? globalThis : this, () => {
  const css = Object.freeze([
    "client/template-editor-runtime/template-editor-runtime.css",
  ]);

  const requiredScripts = Object.freeze([
    "client/features/editor/content-shared.js",
    "client/features/editor/formatting-state.js",
    "client/features/editor/shared-commands.js",
    "client/features/editor/table-cell-utils.js",
    "client/features/editor/table-sizing-utils.js",
    "client/features/editor/table-normalization-utils.js",
    "client/features/editor/table-utils.js",
    "client/features/editor/toolbar-color-markup.js",
    "client/features/editor/toolbar-border-markup.js",
    "client/features/editor/toolbar-markup-helpers.js",
    "client/features/editor/toolbar-markup.js",
    "client/features/editor/toolbar-floating-panel.js",
    "client/features/editor/toolbar-color-ui.js",
    "client/features/editor/toolbar-table-insert-ui.js",
    "client/features/editor/toolbar-font-size-ui.js",
    "client/features/editor/toolbar-border-select-ui.js",
    "client/features/editor/toolbar-ui.js",
    "client/features/editor/toolbar-controls.js",
    "client/features/editor/toolbar-config.js",
    "client/editor-toolbar.js",
    "client/features/template-editor/generated-objects.js",
    "client/features/template-editor/page-settings-core.js",
    "client/features/template-editor/page-settings.js",
    "client/features/template-editor/preview-rendering.js",
    "client/features/template-editor/preview-printing.js",
    "client/features/template-editor/preview.js",
    "client/features/template-editor/image-selection.js",
    "client/features/template-editor/image-session-geometry.js",
    "client/features/template-editor/image-positioning.js",
    "client/features/template-editor/image-move-session.js",
    "client/features/template-editor/image-resize-session.js",
    "client/features/template-editor/image-session.js",
    "client/features/template-editor/image-tools.js",
    "client/features/template-editor/commands-insertion-range.js",
    "client/features/template-editor/commands-insertion-object-fit.js",
    "client/features/template-editor/commands-insertion.js",
    "client/features/template-editor/commands.js",
    "client/features/template-editor/token-content.js",
    "client/features/template-editor/selection-range.js",
    "client/features/template-editor/selection-tokens.js",
    "client/features/template-editor/selection-state.js",
    "client/features/template-editor/selection-history.js",
    "client/features/template-editor/selection.js",
    "client/features/template-editor/editing-token-style.js",
    "client/features/template-editor/editing-runtime.js",
    "client/features/template-editor/table-selection.js",
    "client/features/template-editor/table-cell-only-column-layout.js",
    "client/features/template-editor/table-cell-only-column-transfer.js",
    "client/features/template-editor/table-cell-only-column-resize.js",
    "client/features/template-editor/table-cell-only-row-resize.js",
    "client/features/template-editor/table-resize-hit.js",
    "client/features/template-editor/table-resize-values.js",
    "client/features/template-editor/table-resize-session.js",
    "client/features/template-editor/table-resize.js",
    "client/features/template-editor/table-structure-split.js",
    "client/features/template-editor/table-structure.js",
    "client/features/template-editor/table-sizing-scope.js",
    "client/features/template-editor/table-sizing-values.js",
    "client/features/template-editor/table-sizing.js",
    "client/features/template-editor/table-border-geometry.js",
    "client/features/template-editor/table-border-config.js",
    "client/features/template-editor/table-border-selection.js",
    "client/features/template-editor/table-border-application.js",
    "client/features/template-editor/table-border-actions.js",
    "client/features/template-editor/table-actions.js",
    "client/features/template-editor/table-interaction.js",
    "client/features/template-editor/table-tools-cell-state.js",
    "client/features/template-editor/table-tools-logical-sizing.js",
    "client/features/template-editor/table-tools.js",
    "client/features/template-editor/table-formatting.js",
    "client/features/template-editor/object-flow-reflow.js",
    "client/features/template-editor/table-object-geometry.js",
    "client/features/template-editor/table-object-overlay.js",
    "client/features/template-editor/table-object-sessions.js",
    "client/features/template-editor/table-object.js",
    "client/features/template-editor/document-api.js",
    "client/features/template-editor/keyboard.js",
    "client/features/template-editor/toolbar-rendering.js",
    "client/features/template-editor/toolbar-color-interactions.js",
    "client/features/template-editor/toolbar-interactions.js",
    "client/features/template-editor/toolbar-state.js",
    "client/template-editor-runtime/template-editor-runtime-core.js",
    "client/template-editor-runtime/template-editor-events.js",
    "client/template-editor-runtime/template-editor-runtime-context.js",
    "client/template-editor-runtime/template-editor-runtime-api.js",
    "client/template-editor-runtime/template-editor-runtime-helpers.js",
    "client/template-editor-runtime/template-editor-runtime-wiring.js",
    "client/template-editor-runtime/template-editor-runtime-handler-accessors.js",
    "client/template-editor-runtime/template-editor-runtime-composition.js",
    "client/template-editor-runtime/template-editor-runtime-factory.js",
    "client/template-editor-runtime/template-editor-runtime.js",
  ]);

  const optionalPresetScripts = Object.freeze([]);

  return Object.freeze({
    css,
    optionalPresetScripts,
    requiredScripts,
  });
});
