import { createDefaultTemplateCreateModalState } from "../features/templates/template-create-modal-state.js";

export const appState = {
  currentView: "schoolManagement",
  route: {
    params: {},
    path: "/schools",
    title: "학교 선택",
    view: "schoolManagement",
  },
  auth: {
    authenticated: false,
    enabled: false,
    errorMessage: "",
    loading: false,
    role: "super_admin",
    user: null,
  },
  summary: {
    access: {
      currentRole: "super_admin",
      permissions: {
        deleteProjectData: true,
        deleteSchoolsWithoutPassword: true,
        deleteTemplates: true,
        downloadPdfs: true,
        generatePdfs: true,
        manageAccounts: true,
        manageCandidates: true,
        manageTemplates: true,
        previewTemplates: true,
        viewCandidates: true,
        viewDashboard: true,
        viewGenerations: true,
        viewTemplates: true,
      },
      roleLabel: "슈퍼 관리자",
    },
    admissions: [],
    recentTemplates: [],
    totalCandidates: 0,
    totalRooms: 0,
    totalTemplates: 0,
    warnings: [],
  },
  accounts: {
    errorMessage: "",
    items: [],
    loading: false,
    modal: {
      accountId: "",
      errorMessage: "",
      isOpen: false,
      isSaving: false,
      mode: "create",
      password: "",
      role: "admin",
      userId: "",
      userName: "",
    },
    total: 0,
    uploadModal: {
      errorMessage: "",
      file: null,
      fileName: "",
      isOpen: false,
      isUploading: false,
      result: null,
    },
  },
  schools: {
    detail: null,
    errorMessage: "",
    filters: {
      keyword: "",
    },
    items: [],
    deletingSchoolId: "",
    deletionProgress: {
      candidateCount: 0,
      message: "",
      schoolName: "",
      stageLabel: "",
      templateCount: 0,
    },
    isDeleting: false,
    limit: 30,
    loading: false,
    modal: {
      academicYear: "",
      code: "",
      deletionPassword: "",
      deletionPasswordConfirm: "",
      description: "",
      errorMessage: "",
      isOpen: false,
      isSaving: false,
      logoDataUrl: "",
      mode: "create",
      name: "",
      schoolId: "",
      settingsLoading: false,
    },
    total: 0,
  },
  templates: {
    cardEditor: {
      activeTemplateId: "",
      draftValue: "",
      field: "",
      isSaving: false,
    },
    createModal: createDefaultTemplateCreateModalState(),
    errorMessage: "",
    filters: {
      generationUnit: "",
      keyword: "",
      orientation: "",
      paperPreset: "",
    },
    items: [],
    limit: 100,
    loading: false,
    total: 0,
  },
  candidates: {
    detail: {
      draftRecord: null,
      isOpen: false,
      isPhotoUploading: false,
      isSaving: false,
      originalRecord: null,
      statusMessage: "",
      statusType: "",
    },
    downloadConfirm: {
      count: 0,
      isDownloading: false,
      isOpen: false,
    },
    errorMessage: "",
    filters: {
      admission: "",
      building: "",
      date: "",
      examineeName: "",
      examineeNo: "",
      major: "",
      room: "",
      series: "",
      time: "",
      endTime: "",
      track: "",
      unit: "",
    },
    items: [],
    limit: 12,
    loading: false,
    table: {
      filterMenuKey: "",
      filterMenuPosition: null,
      filterMenuSearch: "",
      filters: {},
      page: 1,
      pageSize: 30,
      pageSizeMenuOpen: false,
      sortRules: [],
    },
    successMessage: "",
    total: 0,
    upload: {
      dataFileName: "",
      dataFile: null,
      errorMessage: "",
      existingDataPolicy: "insert-update",
      isOpen: false,
      isUploading: false,
      mode: "workbook",
      photoFileName: "",
      photoFile: null,
      photoPreview: null,
      photoPreviewToken: "",
      previewProgress: {
        detail: "",
        isIndeterminate: false,
        isActive: false,
        message: "",
        percent: 0,
      },
      progressOverlay: {
        detail: "",
        isIndeterminate: false,
        isOpen: false,
        message: "",
        percent: 0,
        stageLabel: "",
        title: "",
      },
      preview: null,
      successMessage: "",
    },
  },
  schoolSettings: {
    academicYear: "",
    errorMessage: "",
    isDirty: false,
    isSaving: false,
    logoDataUrl: "",
    schoolId: "",
    schoolName: "",
    successMessage: "",
  },
  dataDeletion: {
    activeScope: "",
    isDeleting: false,
    modal: {
      confirmationOpen: false,
      confirmationPhrase: "",
      errorMessage: "",
      filters: {
        admission: "",
        building: "",
        campus: "",
        examDate: "",
        major: "",
        period: "",
        room: "",
        series: "",
        time: "",
        endTime: "",
        track: "",
        unit: "",
      },
      isOpen: false,
      isDeleting: false,
      isLoadingOptions: false,
      isLoadingSummary: false,
      options: {},
      selectedScope: "",
      selectedFilterKeys: [],
      selectedTemplateIds: [],
      summary: null,
      summaryErrorMessage: "",
    },
    progressOverlay: {
      message: "",
      stageLabel: "",
    },
    statusMessage: "",
    statusType: "",
  },
  pdfGenerations: {
    activeGeneration: {
      batchId: "",
      canCancel: false,
      completedCount: 0,
      errorMessage: "",
      estimatedSeconds: 0,
      elapsedSeconds: 0,
      failedCount: 0,
      isOpen: false,
      isCancelling: false,
      label: "",
      progressPercent: 0,
      queuedCount: 0,
      runningCount: 0,
      statusText: "",
      startedAtMs: 0,
      succeededCount: 0,
      totalRequested: 0,
    },
    archiveErrorMessage: "",
    auditErrorMessage: "",
    auditLogs: [],
    auditLoading: false,
    totalAuditLogs: 0,
    cleanupErrorMessage: "",
    cleanupResult: null,
    createModal: {
      activeStepIndex: 0,
      errorMessage: "",
      filters: {
        admission: "",
        building: "",
        campus: "",
        examDate: "",
        major: "",
        period: "",
        room: "",
        series: "",
        time: "",
        endTime: "",
        track: "",
        unit: "",
      },
      isLoadingOptions: false,
      isOpen: false,
      isSubmitting: false,
      options: {},
      selectedFilterKeys: [],
      selectedTemplateId: "",
      templates: [],
      templatePreview: {
        errorMessage: "",
        isLoading: false,
        isOpen: false,
        pdfUrl: "",
        previewHtml: "",
        templateId: "",
        templateName: "",
      },
    },
    downloadModal: {
      errorMessage: "",
      isOpen: false,
      isSubmitting: false,
      mode: "merge",
    },
    generatedResultModal: {
      archiveDownloadUrl: "",
      archiveFileName: "",
      batchId: "",
      errorMessage: "",
      failedCount: 0,
      generationIds: [],
      isOpen: false,
      isSubmitting: false,
      mode: "merge",
      succeededCount: 0,
      templateName: "",
      totalRequested: 0,
    },
    detailModal: {
      generationId: "",
      isOpen: false,
    },
    deleteConfirm: {
      candidateCount: 0,
      count: 0,
      errorMessage: "",
      fileSizeBytes: 0,
      generationIds: [],
      isDeleting: false,
      isOpen: false,
      items: [],
      pageCount: 0,
    },
    errorMessage: "",
    filters: {
      generationUnit: "",
      keyword: "",
      status: "",
    },
    isCreatingArchive: false,
    isBatchRerunning: false,
    isCleaningRetention: false,
    auditTable: {
      filterMenuKey: "",
      filterMenuPosition: null,
      filterMenuSearch: "",
      filters: {},
      page: 1,
      pageSize: 30,
      pageSizeMenuOpen: false,
      sortRules: [{ key: "createdAt", direction: "desc" }],
    },
    items: [],
    lastBatchRerun: null,
    lastRerunGeneration: null,
    limit: 20,
    loading: false,
    rerunErrorMessage: "",
    rerunningGenerationIds: [],
    selectionAnchorGenerationId: "",
    selectedGenerationIds: [],
    table: {
      filterMenuKey: "",
      filterMenuPosition: null,
      filterMenuSearch: "",
      filters: {},
      page: 1,
      pageSize: 30,
      pageSizeMenuOpen: false,
      sortRules: [{ key: "sequenceNumber", direction: "asc" }],
    },
    total: 0,
  },
  pdfGenerationDetail: {
    errorMessage: "",
    item: null,
    loading: false,
  },
  templateEditor: {
    dataTags: {
      groups: [],
    },
    dataTagSampleModal: {
      draftEmptyValueData: {},
      draftValues: {},
      isOpen: false,
    },
    dataTagEmptyValueData: {},
    dataTagSampleValues: {},
    documentOverflowMessage: "",
    errorMessage: "",
    generationUnitModal: {
      isOpen: false,
    },
    imageMoveSession: null,
    imageResizeSession: null,
    isDirty: false,
    isPreviewLoading: false,
    isPreviewOpen: false,
    isSaving: false,
    isSavingDataTagSettings: false,
    hasDocumentOverflow: false,
    lastLoadedTemplateId: "",
    loading: false,
    previewCandidateCount: 0,
    previewErrorMessage: "",
    previewHtml: "",
    previewPageCount: 0,
    previewPdfUrl: "",
    previewWarnings: [],
    savedTemplateSnapshot: null,
    selectedImageElement: null,
    selectedPageId: "",
    template: null,
  },
  ui: {
    activeSchoolId: "",
    activeTemplateId: "",
    busyMessage: "",
    modalClosePrompt: {
      isOpen: false,
      isSaving: false,
      message: "",
      modalId: "",
    },
  },
};
