const candidateFieldMap = Object.freeze({
  "candidate.admissionYear": "school_settings.academic_year",
  "candidate.designatedSort": "designated_sort",
  "candidate.admissionRoundName": "track",
  "candidate.campusName": "campus",
  "candidate.campusCode": "campus_code",
  "candidate.admissionTypeName": "admission",
  "candidate.admissionTypeCode": "admission_code",
  "candidate.seriesName": "series",
  "candidate.seriesCode": "series_code",
  "candidate.departmentName": "unit",
  "candidate.departmentCode": "unit_code",
  "candidate.majorName": "major",
  "candidate.majorCode": "major_code",
  "candidate.examDate": "exam_date",
  "candidate.examStartTime": "time",
  "candidate.examEndTime": "end_time",
  "candidate.periodName": "period",
  "candidate.periodCode": "period_code",
  "candidate.buildingName": "building",
  "candidate.buildingCode": "building_code",
  "candidate.roomName": "room",
  "candidate.roomCode": "room_code",
  "candidate.examNo": "examinee_no",
  "candidate.temporaryNo": "temporary_no",
  "candidate.name": "name",
  "candidate.birthDate": "birth_date",
  "candidate.groupName": "group_name",
  "candidate.opt1": "opt1",
  "candidate.opt2": "opt2",
  "candidate.opt3": "opt3",
  "candidate.opt4": "opt4",
  "candidate.opt5": "opt5",
  "candidate.photo": "photo_name",
});

module.exports = {
  candidateFieldMap,
};
